Publish imu data in SI Unit and set Frame name with parameter
KonboiOne/livox_ros2_driver pull request #1
Opened 2024-04-17 13:27 UTC by Scout22

2024-04-17 14:01 UTC, kamibo requested changes

2024-04-17 14:01 UTC, kamibo commented on livox_ros2_driver/livox_ros2_driver/livox_ros2_driver.cpp
> +  this->declare_parameter("frame_id_imu.", "livox_front");
Extra `.` ?

2024-04-17 14:01 UTC, kamibo commented on livox_ros2_driver/livox_ros2_driver/lddc.h
> +       std::string &frame_id, std::string &frame_id_imu);
I don't get why it was already not `const &` but no big deal..

2024-04-17 14:52 UTC, Scout22 commented on livox_ros2_driver/livox_ros2_driver/lddc.h
> +       std::string &frame_id, std::string &frame_id_imu);
Done

2024-04-18 07:17 UTC, kamibo approved these changes

2024-04-22 07:44 UTC, merged